/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.avaliacaolp;

import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author Rodrigo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pbCpu = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        lbCpu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbMaxCpu = new javax.swing.JLabel();
        lbMinCpu = new javax.swing.JLabel();
        lbMediaCpu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pbDisco = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        lbDisco = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbMaxDisco = new javax.swing.JLabel();
        lbMinDisco = new javax.swing.JLabel();
        lbMediaDisco = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pbMemoria = new javax.swing.JProgressBar();
        jLabel17 = new javax.swing.JLabel();
        lbMemoria = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbMaxMemoria = new javax.swing.JLabel();
        lbMinMemoria = new javax.swing.JLabel();
        lbMediaMemoria = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Disco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("1.5GHz");

        lbCpu.setForeground(new java.awt.Color(51, 51, 51));
        lbCpu.setText("...");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Máximo: ");

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Mínimo: ");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Média: ");

        lbMaxCpu.setForeground(new java.awt.Color(51, 51, 51));
        lbMaxCpu.setText("...");

        lbMinCpu.setForeground(new java.awt.Color(51, 51, 51));
        lbMinCpu.setText("...");

        lbMediaCpu.setForeground(new java.awt.Color(51, 51, 51));
        lbMediaCpu.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lbCpu))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMinCpu))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMaxCpu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMediaCpu))
                    .addComponent(pbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(pbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCpu)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbMaxCpu)
                    .addComponent(jLabel5)
                    .addComponent(lbMediaCpu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbMinCpu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Disco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("465GB");

        lbDisco.setForeground(new java.awt.Color(51, 51, 51));
        lbDisco.setText("...");

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Máximo: ");

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Mínimo: ");

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Média: ");

        lbMaxDisco.setForeground(new java.awt.Color(51, 51, 51));
        lbMaxDisco.setText("...");

        lbMinDisco.setForeground(new java.awt.Color(51, 51, 51));
        lbMinDisco.setText("...");

        lbMediaDisco.setForeground(new java.awt.Color(51, 51, 51));
        lbMediaDisco.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lbDisco))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMinDisco))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMaxDisco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMediaDisco))
                    .addComponent(pbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addComponent(pbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDisco)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbMaxDisco)
                    .addComponent(jLabel13)
                    .addComponent(lbMediaDisco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbMinDisco))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Disco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));

        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("2.0GB");

        lbMemoria.setForeground(new java.awt.Color(51, 51, 51));
        lbMemoria.setText("...");

        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Máximo: ");

        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Mínimo: ");

        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Média: ");

        lbMaxMemoria.setForeground(new java.awt.Color(51, 51, 51));
        lbMaxMemoria.setText("...");

        lbMinMemoria.setForeground(new java.awt.Color(51, 51, 51));
        lbMinMemoria.setText("...");

        lbMediaMemoria.setForeground(new java.awt.Color(51, 51, 51));
        lbMediaMemoria.setText("...");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lbMemoria))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMinMemoria))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMaxMemoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMediaMemoria))
                    .addComponent(pbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17))
                    .addComponent(pbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMemoria)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lbMaxMemoria)
                    .addComponent(jLabel21)
                    .addComponent(lbMediaMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lbMinMemoria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Fazer Leitura de Dados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    ArrayList<Double> cpuList = new ArrayList<Double>();
//    ArrayList<Double> discoList = new ArrayList<Double>();
//    ArrayList<Double> memoriaList = new ArrayList<Double>();
    
    Double cpu = 1.5;
    Double disco = 465.0;
    Double memoria = 2.0;
    Integer contador = 0;
    
    Double maximo_cpu = 0.0;
    Double min_cpu = cpu;
    Double sum_cpu = 0.0;
    
    
    Double maximo_disco = 0.0;
    Double min_disco = disco;
    Double sum_disco = 0.0;
    
    Double maximo_memoria = 0.0;
    Double min_memoria = memoria;
    Double sum_memoria = 0.0;
    
    
//    private Double[] analisaArray(ArrayList<Double> array){
//        Double max=0.0, min=0.0, media=0.0, sum=0.0;
//        for(int i=0;i<array.size();i++){
//            double aux = array.get(i);
//            max = aux;
//            min = aux;
//            if(aux>max){
//                max = aux;
//            }else if(aux<min){
//                min = aux;
//            }
//            sum += aux;
//        }
//        media = sum/array.size();
//        Double[] estatisticas = {max, min, media};
//        return estatisticas;
//    }
    public String formata(Double n){
        return String.format("%.1f", n);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Random random = new Random();
        Double rdn_cpu = random.nextDouble() * cpu;
        Double rdn_disco = random.nextDouble()* disco;
        Double rdn_memoria = random.nextDouble()*memoria;
        
        contador++;
        
        if(rdn_cpu>maximo_cpu){
            maximo_cpu = rdn_cpu;
        }
        if(rdn_cpu<min_cpu){
            min_cpu = rdn_cpu;
        }
        sum_cpu += rdn_cpu;
        
        
        if(rdn_disco>maximo_disco){
            maximo_disco = rdn_disco;
        }
        if(rdn_disco<min_disco){
            min_disco = rdn_disco;
        }
        sum_disco += rdn_disco;
        
        
        if(rdn_memoria>maximo_memoria){
            maximo_memoria = rdn_memoria;
        }
        if(rdn_memoria<min_memoria){
            min_memoria = rdn_memoria;
        }
        sum_memoria += rdn_memoria;
        
        
//        cpuList.add(rdn_cpu);
//        discoList.add(rdn_disco);
//        memoriaList.add(rdn_memoria);
        
//        Double[] scpu = analisaArray(cpuList);
//        Double[] sdisco = analisaArray(discoList);
//        Double[] smemoria = analisaArray(memoriaList);
                
        Double perc_cpu = (rdn_cpu*100)/cpu;
        Double perc_disco = (rdn_disco*100)/disco;
        Double perc_memoria = (rdn_memoria*100)/memoria;
        
        System.out.println(String.format
            ("CPU\nValor máximo: %.1f\nValor gerado: %.1f\nPorcentagem : %.1f",
                    cpu, rdn_cpu, perc_cpu));
        
        
        System.out.println(String.format
            ("Disco\nValor máximo: %.1f\nValor gerado: %.1f\nPorcentagem : %.1f",
                    disco, rdn_disco, perc_disco));
        
        
        System.out.println(String.format
            ("Memória\nValor máximo: %.1f\nValor gerado: %.1f\nPorcentagem : %.1f",
                    memoria, rdn_memoria, perc_memoria));
        
        pbCpu.setValue(perc_cpu.intValue());
        pbDisco.setValue(perc_disco.intValue());
        pbMemoria.setValue(perc_memoria.intValue());
        
        lbCpu.setText(String.format("%.1f%% --> %.1fGHz", perc_cpu, rdn_cpu));
        lbDisco.setText(String.format("%.1f%% --> %.1fGB", perc_disco, rdn_disco));
        lbMemoria.setText(String.format("%.1f%% --> %.1fGB", perc_memoria, rdn_memoria));
        
        
        lbMaxCpu.setText(formata(maximo_cpu));
        lbMinCpu.setText(formata(min_cpu));
        lbMediaCpu.setText(formata(sum_cpu/contador));
        
        lbMaxDisco.setText(formata(maximo_disco));
        lbMinDisco.setText(formata(min_disco));
        lbMediaDisco.setText(formata(sum_disco/contador));
        
        lbMaxMemoria.setText(formata(maximo_memoria));
        lbMinMemoria.setText(formata(min_memoria));
        lbMediaMemoria.setText(formata(sum_memoria/contador));
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbCpu;
    private javax.swing.JLabel lbDisco;
    private javax.swing.JLabel lbMaxCpu;
    private javax.swing.JLabel lbMaxDisco;
    private javax.swing.JLabel lbMaxMemoria;
    private javax.swing.JLabel lbMediaCpu;
    private javax.swing.JLabel lbMediaDisco;
    private javax.swing.JLabel lbMediaMemoria;
    private javax.swing.JLabel lbMemoria;
    private javax.swing.JLabel lbMinCpu;
    private javax.swing.JLabel lbMinDisco;
    private javax.swing.JLabel lbMinMemoria;
    private javax.swing.JProgressBar pbCpu;
    private javax.swing.JProgressBar pbDisco;
    private javax.swing.JProgressBar pbMemoria;
    // End of variables declaration//GEN-END:variables
}
